### ISSUE TITLE
Can't load shared library

### ISSUE THREAD

**Issue by inferrna** [katyo/oboe-rs#5]
**1.** When build shared `oboe = { git = "https://github.com/katyo/oboe-rs.git", features = ["generate-bindings", "compile-library"] }` got error
`Load libary ERROR: java.lang.UnsatisfiedLinkError: dlopen failed: library "liboboe-ext.so" not found`

the library itself successful built and exists:
```bash
-rwxr-xr-x 1 inferno inferno 383K апр  4 02:12 ./target/aarch64-linux-android/release/build/oboe-sys-de0d76fb093f1667/out/build/liboboe-ext.so
-rwxr-xr-x 1 inferno inferno 342K апр  4 02:12 ./target/arm-linux-androideabi/release/build/oboe-sys-a839339640dddce0/out/build/liboboe-ext.so
```

**2.** With static link `oboe = { git = "https://github.com/katyo/oboe-rs.git", features = ["generate-bindings", "compile-library", "static-link"] }` got another
`Load libary ERROR: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZNSt6__ndk15mutex4lockEv" referenced by "/data/app/net.akaame.myapplication-wI4tFkDRFJul-OBc9iSySA==/base.apk!/lib/armeabi/libmobcore.so"`
Seems like it comes from `libc++_shared.so` which needed by `liboboe-ext.so`

**Comment by katyo** [comment]
This because you need include all dependent shared libs (particularly liboboe-ext.so and libc++_shared.so in our case) within your application package.
Depending from your packaging tool this task can be automated or you must to do it manually.
I automated this in `cargo-apk` by using readelf to find all needed shared objects recursively.

Static linking can solve any similar problems. But I had strange linking issues when tried to link rust and c++ code statically (with crate_type="cdylib") so I use dynamic linking by default.
You can try "static-link" feature, may be it helps.

**Comment by endragor** [comment]
I've tried to use this library and got a similar problem when using `cargo apk build`. Specifically, `liboboe-ext.so` resides under `target/debug/liboboe-ext/aarch64/liboboe-ext.so`, but it doesn't get picked up by `cargo apk build` and this message appears during the build:

```
Shared library "liboboe-ext.so" not found.
```

Could you please clarify how it should be set up so that the .so gets included in the .apk?

```
$ cargo --version
cargo 1.43.0 (2cbe9048e 2020-05-03)
```
cargo-apk is v0.5.1.

I guess this question is pretty much the same as https://github.com/rust-windowing/android-ndk-rs/issues/64

**Comment by katyo** [comment]
This sounds so strange because cargo apk should looks through all known paths.
We missing tests in `cargo-apk`, so possibly, this problem happened again after @dvc96ch rewritten this tool from scratch.

UPD:
Originally I got search paths also from rustc args:
https://github.com/rust-windowing/android-rs-glue/pull/260/files#diff-85629c31011b4a1ea5f77781f277ab4bR336
https://github.com/rust-windowing/android-rs-glue/pull/260/files#diff-85629c31011b4a1ea5f77781f277ab4bR461-R478
But, it seems, this code does not migrated by @dvc94ch to a new `cargo-apk`.
https://github.com/rust-windowing/android-ndk-rs/blob/bb11c390893c965f5b765675f87a101a03cb013a/cargo-apk/src/apk.rs#L92
As you can see only "deps" directory will be looked for the libs, so this is `cargo-apk`s bug.

**Comment by endragor** [comment]
If there is a problem with including third-party .so to the .apk, perhaps you could look into making static linking work? Last time I tried, it didn't work for me. I'd really appreciate your help!

**Comment by katyo** [comment]
> If there is a problem with including third-party .so to the .apk, perhaps you could look into making static linking work? Last time I tried, it didn't work for me. I'd really appreciate your help!

No, static linking with rust and c++ does not works for me too.
IIRC this issue related to C++ runtime, specifically with initializing of static variables.
It works fine only when no static vars on C++ side.

Possibly we may patch oboe library by replacing statically initialized variables with static consts but with no any warranties that it won't be added in future. (google/oboe#745)

**Comment by katyo** [comment]
For now static linking works fine (#12).
